### ISSUE TITLE
Do styles for gallery in example

### ISSUE THREAD

**Issue by uralbash** [ITCase/pyramid_pages#40]
![_154](https://cloud.githubusercontent.com/assets/619015/8057219/bfd5a908-0ec8-11e5-8b21-ebe3d6c8f89a.png)

**Comment by uralbash** [comment]
Image thumbnails - https://api.imgur.com/models/image

**Comment by movie4** [comment]
30426322435e9c2ab13fd19320fe54ace5e36405

**Comment by uralbash** [comment]
Need same style as left menu

![_158](https://cloud.githubusercontent.com/assets/619015/8230945/27c76350-15de-11e5-9e78-c036020f5a69.png)

**Comment by uralbash** [comment]
Do not truncate images.

![_160](https://cloud.githubusercontent.com/assets/619015/8231073/4083746e-15df-11e5-9bd8-b20ac11b7a4e.png)

**Comment by uralbash** [comment]
Need to close fotorama when click out of popup
